# Generated by Django 5.2.3 on 2025-07-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_task_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('datetime', models.DateTimeField()),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.task')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.teammember')),
            ],
        ),
    ]
