# Generated by Django 5.2.3 on 2025-07-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_assignedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.team'),
        ),
    ]
