# Generated by Django 5.2.3 on 2025-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='team_member',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='team_members',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_tasks', to='system.teammember'),
        ),
    ]
