# Generated by Django 5.2.3 on 2025-07-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_assignedtask_team_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to='system.teammember'),
        ),
    ]
