# Generated by Django 5.2.3 on 2025-07-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_alter_assignedtask_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='team_members',
        ),
    ]
