# Generated by Django 5.2.3 on 2025-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_remove_assignedtask_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedtask',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
